<a href="https://colab.research.google.com/github/amay1212/voice-clone-real-time/blob/main/coqui_tts.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!git clone https://github.com/coqui-ai/TTS

Cloning into 'TTS'...
remote: Enumerating objects: 32844, done.
remote: Total 32844 (delta 0), reused 0 (delta 0), pack-reused 32844
Receiving objects: 100% (32844/32844), 166.21 MiB | 22.16 MiB/s, done.
Resolving deltas: 100% (23820/23820), done.


In [ ]:
%cd TTS

/content/TTS


In [ ]:
!ls -l

total 8
drwxr-xr-x  1 root root 4096 Jul  3 13:21 sample_data
drwxr-xr-x 12 root root 4096 Jul  4 09:44 TTS


In [8]:
!ls -l

total 152
-rw-r--r--  1 root root   589 Jul  4 09:44 CITATION.cff
-rw-r--r--  1 root root  5488 Jul  4 09:44 CODE_OF_CONDUCT.md
-rw-r--r--  1 root root  4106 Jul  4 09:44 CODE_OWNERS.rst
-rw-r--r--  1 root root  6231 Jul  4 09:44 CONTRIBUTING.md
-rw-r--r--  1 root root   578 Jul  4 09:44 Dockerfile
drwxr-xr-x  2 root root  4096 Jul  4 09:44 dockerfiles
drwxr-xr-x  3 root root  4096 Jul  4 09:44 docs
-rw-r--r--  1 root root  1892 Jul  4 09:44 hubconf.py
drwxr-xr-x  2 root root  4096 Jul  4 09:44 images
-rw-r--r--  1 root root 16726 Jul  4 09:44 LICENSE.txt
-rw-r--r--  1 root root  2246 Jul  4 09:44 Makefile
-rw-r--r--  1 root root   362 Jul  4 09:44 MANIFEST.in
drwxr-xr-x  3 root root  4096 Jul  4 09:44 notebooks
-rw-r--r--  1 root root   282 Jul  4 09:44 pyproject.toml
-rw-r--r--  1 root root 17429 Jul  4 09:44 README.md
drwxr-xr-x  9 root root  4096 Jul  4 09:44 recipes
-rw-r--r--  1 root root    42 Jul  4 09:44 requirements.dev.txt
-rw-r--r--  1 root root   154 Jul  4 09:44 requireme

In [9]:
!pip install trainer

In [2]:
!pip install -r requirements.txt

Ignoring numpy: markers 'python_version > "3.10"' don't match your environment
Ignoring numba: markers 'python_version < "3.9"' don't match your environment


In [11]:
!ls -l

total 152
-rw-r--r--  1 root root   589 Jul  4 09:44 CITATION.cff
-rw-r--r--  1 root root  5488 Jul  4 09:44 CODE_OF_CONDUCT.md
-rw-r--r--  1 root root  4106 Jul  4 09:44 CODE_OWNERS.rst
-rw-r--r--  1 root root  6231 Jul  4 09:44 CONTRIBUTING.md
-rw-r--r--  1 root root   578 Jul  4 09:44 Dockerfile
drwxr-xr-x  2 root root  4096 Jul  4 09:44 dockerfiles
drwxr-xr-x  3 root root  4096 Jul  4 09:44 docs
-rw-r--r--  1 root root  1892 Jul  4 09:44 hubconf.py
drwxr-xr-x  2 root root  4096 Jul  4 09:44 images
-rw-r--r--  1 root root 16726 Jul  4 09:44 LICENSE.txt
-rw-r--r--  1 root root  2246 Jul  4 09:44 Makefile
-rw-r--r--  1 root root   362 Jul  4 09:44 MANIFEST.in
drwxr-xr-x  3 root root  4096 Jul  4 09:44 notebooks
-rw-r--r--  1 root root   282 Jul  4 09:44 pyproject.toml
-rw-r--r--  1 root root 17429 Jul  4 09:44 README.md
drwxr-xr-x  9 root root  4096 Jul  4 09:44 recipes
-rw-r--r--  1 root root    42 Jul  4 09:44 requirements.dev.txt
-rw-r--r--  1 root root   154 Jul  4 09:44 requireme

In [12]:
%cd TTS

/content/TTS/TTS


In [3]:
!ls -l

total 156
-rw-r--r--  1 root root   589 Jul  4 09:44 CITATION.cff
-rw-r--r--  1 root root  5488 Jul  4 09:44 CODE_OF_CONDUCT.md
-rw-r--r--  1 root root  4106 Jul  4 09:44 CODE_OWNERS.rst
-rw-r--r--  1 root root  6231 Jul  4 09:44 CONTRIBUTING.md
-rw-r--r--  1 root root   578 Jul  4 09:44 Dockerfile
drwxr-xr-x  2 root root  4096 Jul  4 09:44 dockerfiles
drwxr-xr-x  3 root root  4096 Jul  4 09:44 docs
-rw-r--r--  1 root root  1892 Jul  4 09:44 hubconf.py
drwxr-xr-x  2 root root  4096 Jul  4 09:44 images
-rw-r--r--  1 root root 16726 Jul  4 09:44 LICENSE.txt
-rw-r--r--  1 root root  2246 Jul  4 09:44 Makefile
-rw-r--r--  1 root root   362 Jul  4 09:44 MANIFEST.in
drwxr-xr-x  3 root root  4096 Jul  4 09:44 notebooks
drwxr-xr-x  2 root root  4096 Jul  4 11:08 __pycache__
-rw-r--r--  1 root root   282 Jul  4 09:44 pyproject.toml
-rw-r--r--  1 root root 17429 Jul  4 09:44 README.md
drwxr-xr-x  9 root root  4096 Jul  4 09:44 recipes
-rw-r--r--  1 root root    42 Jul  4 09:44 requirements.dev.t

In [20]:
%cd TTS/

/content/TTS/TTS


In [25]:
%cd ..

/content/TTS


In [4]:
import os
from TTS.api import TTS

# Get device ('cuda' or 'cpu')
# device="mps"

# txt="This makes sense, hey man can you hear the voice cloned."


# #Define audio sample
# # sample="../my-voices/ultron-es/mix.wav"
# samples = os.listdir("../input")

# print(samples)
# tts1 = TTS("tts_models/multilingual/multi-dataset/xtts_v2").to("gpu")
# for sample in samples:
#     if sample.endswith('.wav'):
#         print(sample)

#         tts1.tts_to_file(txt, speaker_wav=f"../input/{sample}", language="en", file_path=f"../output/{sample}_output.wav")

In [30]:
%cd ..

/content


In [5]:
import torch
print(torch.cuda.is_available())

True


In [ ]:
device="cuda"

txt="This makes sense, hey man can you hear the voice cloned. this is just testing for me, lets do it"


#Define audio sample
# sample="../my-voices/ultron-es/mix.wav"
samples = os.listdir("../input")

print(samples)
tts1 = TTS("tts_models/multilingual/multi-dataset/xtts_v2").to(device)
for sample in samples:
    if sample.endswith('.wav'):
        print(sample)

        tts1.tts_to_file(txt, speaker_wav=f"../input/{sample}", language="en", file_path=f"../output/{sample.replace('.wav', '')}_output.wav")

['robert downey jr.wav', 'mix-en.wav', 'fate.wav', 'morgan-free.wav', 'batman.wav', 'john connor batman.wav', 'jesse-pinkman-voicemail-breaking-bad-made-with-Voicemod.wav', 'walter.wav', 'leo.wav', 'jack sparrow.wav']
 > tts_models/multilingual/multi-dataset/xtts_v2 is already downloaded.
 > Using model: xtts
robert downey jr.wav
 > Text splitted to sentences.
['This makes sense, hey man can you hear the voice cloned.']
 > Processing time: 2.3784725666046143
 > Real-time factor: 0.4912082280611395
mix-en.wav
 > Text splitted to sentences.
['This makes sense, hey man can you hear the voice cloned.']
 > Processing time: 2.224961519241333
 > Real-time factor: 0.5307729087250237
fate.wav
 > Text splitted to sentences.
['This makes sense, hey man can you hear the voice cloned.']
 > Processing time: 1.9904537200927734
 > Real-time factor: 0.5056394530880836
morgan-free.wav
 > Text splitted to sentences.
['This makes sense, hey man can you hear the voice cloned.']
 > Processing time: 3.295572

In [ ]:
txt="This makes sense, hey man can you hear the voice cloned. this is just testing for me, lets do it"
for sample in samples[:1]:
    if sample.endswith('.wav'):
        print(sample)

        tts1.tts_to_file(txt, speaker_wav=f"../input/{sample}", language="en", file_path=f"../output/{sample.replace('.wav', '')}_output.wav")

robert downey jr.wav
 > Text splitted to sentences.
['This makes sense, hey man can you hear the voice cloned.', 'this is just testing for me, lets do it']
 > Processing time: 4.640094757080078
 > Real-time factor: 0.4995024673567398


In [ ]:
tts1.models

NameError: name 'tts1' is not defined

In [ ]:
!pwd

/content/TTS


In [ ]:
!ls -l

total 152
-rw-r--r--  1 root root   589 Jul  4 09:44 CITATION.cff
-rw-r--r--  1 root root  5488 Jul  4 09:44 CODE_OF_CONDUCT.md
-rw-r--r--  1 root root  4106 Jul  4 09:44 CODE_OWNERS.rst
-rw-r--r--  1 root root  6231 Jul  4 09:44 CONTRIBUTING.md
-rw-r--r--  1 root root   578 Jul  4 09:44 Dockerfile
drwxr-xr-x  2 root root  4096 Jul  4 09:44 dockerfiles
drwxr-xr-x  3 root root  4096 Jul  4 09:44 docs
-rw-r--r--  1 root root  1892 Jul  4 09:44 hubconf.py
drwxr-xr-x  2 root root  4096 Jul  4 09:44 images
-rw-r--r--  1 root root 16726 Jul  4 09:44 LICENSE.txt
-rw-r--r--  1 root root  2246 Jul  4 09:44 Makefile
-rw-r--r--  1 root root   362 Jul  4 09:44 MANIFEST.in
drwxr-xr-x  3 root root  4096 Jul  4 09:44 notebooks
-rw-r--r--  1 root root   282 Jul  4 09:44 pyproject.toml
-rw-r--r--  1 root root 17429 Jul  4 09:44 README.md
drwxr-xr-x  9 root root  4096 Jul  4 09:44 recipes
-rw-r--r--  1 root root    42 Jul  4 09:44 requirements.dev.txt
-rw-r--r--  1 root root   154 Jul  4 09:44 requireme

/bin/bash: line 1: cd: /home/user/.local/share/: No such file or directory


In [ ]:
!pip install deepspeed

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 9.5 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 54.0/54.0 kB 8.6 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 307.2/307.2 kB 15.2 MB/s eta 0:00:00
  Created wheel for deepspeed: filename=deepspeed-0.14.4-py3-none-any.whl size=1445518 sha256=02e9a6a1064be97fa816628e0d79b5ede39bcd30c274869940f2610d4e4fe6ab
  Stored in directory: /root/.cache/pip/wheels/8e/bc/a3/608e90bbb301848b78fd75d24d6d43ba3074de968fc0e397ac
Successfully built deepspeed


In [ ]:
!pip install transformers==4.40.2

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.0/9.0 MB 24.6 MB/s eta 0:00:00
  Attempting uninstall: transformers
    Found existing installation: transformers 4.41.2
    Uninstalling transformers-4.41.2:
      Successfully uninstalled transformers-4.41.2


In [6]:
import os
import time
import torch
import torchaudio
from TTS.tts.configs.xtts_config import XttsConfig
from TTS.tts.models.xtts import Xtts

print("Loading model...")
config = XttsConfig()
config.load_json("/content/TTS/TTS/config.json")
model = Xtts.init_from_config(config)
model.load_checkpoint(config, checkpoint_dir="/content/TTS/recipes/ljspeech/xtts_v2/", use_deepspeed=True, vocab_path="/content/TTS/recipes/ljspeech/vocab.json")
model.cuda()

print("Computing speaker latents...")
# gpt_cond_latent, speaker_embedding = model.get_conditioning_latents(audio_path=["reference.wav"])

# print("Inference...")
# t0 = time.time()
# chunks = model.inference_stream(
#     "It took me quite a long time to develop a voice and now that I have it I am not going to be silent.",
#     "en",
#     gpt_cond_latent,
#     speaker_embedding
# )

# wav_chuncks = []
# for i, chunk in enumerate(chunks):
#     if i == 0:
#         print(f"Time to first chunck: {time.time() - t0}")
#     print(f"Received chunk {i} of audio length {chunk.shape[-1]}")
#     wav_chuncks.append(chunk)
# wav = torch.cat(wav_chuncks, dim=0)
# torchaudio.save("xtts_streaming.wav", wav.squeeze().unsqueeze(0).cpu(), 24000)

Loading model...
[2024-07-04 11:11:31,426] [INFO] [real_accelerator.py:203:get_accelerator] Setting ds_accelerator to cuda (auto detect)
 [WARNING]  async_io requires the dev libaio .so object and headers but these were not found.
 [WARNING]  async_io: please install the libaio-dev package with apt
 [WARNING]  If libaio is already installed (perhaps from source), try setting the CFLAGS and LDFLAGS environment variables to where it can be found.
 [WARNING]  Please specify the CUTLASS repo directory as environment variable $CUTLASS_PATH
 [WARNING]  sparse_attn requires a torch version >= 1.5 and < 2.0 but detected 2.3
 [WARNING]  using untested triton version (2.3.0), only 1.0.0 is known to be compatible
[2024-07-04 11:11:32,457] [INFO] [logging.py:96:log_dist] [Rank -1] DeepSpeed info: version=0.14.4, git-hash=unknown, git-branch=unknown
[2024-07-04 11:11:32,459] [WARNING] [config_utils.py:69:_process_deprecated_field] Config parameter replace_method is deprecated. This parameter is no 

Using /root/.cache/torch_extensions/py310_cu121 as PyTorch extensions root...
Detected CUDA files, patching ldflags
Emitting ninja build file /root/.cache/torch_extensions/py310_cu121/transformer_inference/build.ninja...
/usr/local/lib/python3.10/dist-packages/torch/utils/cpp_extension.py:1967: UserWarning: TORCH_CUDA_ARCH_LIST is not set, all archs for visible cards are included for compilation. 
If this is not desired, please set os.environ['TORCH_CUDA_ARCH_LIST'].
  warnings.warn(
Building extension module transformer_inference...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)


Time to load transformer_inference op: 38.88623905181885 seconds
[2024-07-04 11:12:11,545] [INFO] [logging.py:96:log_dist] [Rank -1] DeepSpeed-Inference config: {'layer_id': 0, 'hidden_size': 1024, 'intermediate_size': 4096, 'heads': 16, 'num_hidden_layers': -1, 'dtype': torch.float32, 'pre_layer_norm': True, 'norm_type': <NormType.LayerNorm: 1>, 'local_rank': -1, 'stochastic_mode': False, 'epsilon': 1e-05, 'mp_size': 1, 'scale_attention': True, 'triangular_masking': True, 'local_attention': False, 'window_size': 1, 'rotary_dim': -1, 'rotate_half': False, 'rotate_every_two': True, 'return_tuple': True, 'mlp_after_attn': True, 'mlp_act_func_type': <ActivationFuncType.GELU: 1>, 'specialized_mode': False, 'training_mp_size': 1, 'bigscience_bloom': False, 'max_out_tokens': 1024, 'min_out_tokens': 1, 'scale_attn_by_inverse_layer_idx': False, 'enable_qkv_quantization': False, 'use_mup': False, 'return_single_tuple': False, 'set_empty_params': False, 'transposed_mode': False, 'use_triton': Fa

Loading extension module transformer_inference...


Computing speaker latents...


In [ ]:
# !pip install transformers==4.40.2

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.0/9.0 MB 22.5 MB/s eta 0:00:00
  Attempting uninstall: transformers
    Found existing installation: transformers 4.41.2
    Uninstalling transformers-4.41.2:
      Successfully uninstalled transformers-4.41.2


In [16]:
gpt_cond_latent, speaker_embedding = model.get_conditioning_latents(audio_path=["../input/batman.wav"])
# print(speaker_embedding)
print("Inference...")
t0 = time.time()
chunks = model.inference_stream(
    "It took me quite a long time to develop a voice and now that I have it I am not going to be silent.",
    "en",
    gpt_cond_latent,
    speaker_embedding
)

wav_chuncks = []
for i, chunk in enumerate(chunks):
    # print("test")
    # if i == 0:


    print(f"Time to first chunck: {round(time.time() - t0, 3)}")

    print(f"Received chunk {i} of audio length {chunk.shape[-1]}")
    wav_chuncks.append(chunk)
wav = torch.cat(wav_chuncks, dim=0)
torchaudio.save("../output/xtts_streaming.wav", wav.squeeze().unsqueeze(0).cpu(), 24000)

Inference...
Time to first chunck: 0.221
Received chunk 0 of audio length 21248
Time to first chunck: 0.435
Received chunk 1 of audio length 22272
Time to first chunck: 0.649
Received chunk 2 of audio length 22272
Time to first chunck: 0.868
Received chunk 3 of audio length 22272
Time to first chunck: 1.084
Received chunk 4 of audio length 22272
Time to first chunck: 1.298
Received chunk 5 of audio length 22272
Time to first chunck: 1.521
Received chunk 6 of audio length 22272
Time to first chunck: 1.74
Received chunk 7 of audio length 22272
Time to first chunck: 1.893
Received chunk 8 of audio length 3328


In [10]:
# for i in chunks:
#   print(i)

/content/TTS/TTS/tts/layers/xtts/stream_generator.py:138: UserWarning: You have modified the pretrained model configuration to control generation. This is a deprecated strategy to control generation and will be removed soon, in a future version. Please use a generation configuration file (see https://huggingface.co/docs/transformers/main_classes/text_generation)
  warnings.warn(


tensor([-0.0140, -0.0153, -0.0162,  ...,  0.0358,  0.0480,  0.0728],
       device='cuda:0')
tensor([ 0.0790,  0.1372,  0.1455,  ..., -0.0449, -0.0848, -0.1164],
       device='cuda:0')


/usr/local/lib/python3.10/dist-packages/torch/nn/modules/conv.py:306: UserWarning: Plan failed with a cudnnException: CUDNN_BACKEND_EXECUTION_PLAN_DESCRIPTOR: cudnnFinalize Descriptor Failed cudnn_status: CUDNN_STATUS_NOT_SUPPORTED (Triggered internally at ../aten/src/ATen/native/cudnn/Conv_v8.cpp:919.)
  return F.conv1d(input, weight, bias, self.stride,


tensor([-0.1794, -0.2417, -0.2622,  ..., -0.0023, -0.0057, -0.0050],
       device='cuda:0')
tensor([-0.0029,  0.0005,  0.0091,  ...,  0.3242,  0.3568,  0.3930],
       device='cuda:0')
tensor([ 0.3851,  0.3013,  0.2713,  ...,  0.0009, -0.0004, -0.0008],
       device='cuda:0')
tensor([-0.0022, -0.0035, -0.0038,  ..., -0.0637, -0.0576, -0.0575],
       device='cuda:0')
tensor([-5.4087e-02, -4.7764e-02, -4.6252e-02,  ..., -2.1798e-05,
        -1.9942e-05, -1.5462e-05], device='cuda:0')
